// source: autocomplete.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.me.world.usa.service.AutoCompleteResponse', null, global);
goog.exportSymbol('proto.me.world.usa.service.AutoCompleteResponse.Item', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.me.world.usa.service.AutoCompleteResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.me.world.usa.service.AutoCompleteResponse.repeatedFields_, null);
};
goog.inherits(proto.me.world.usa.service.AutoCompleteResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.me.world.usa.service.AutoCompleteResponse.displayName = 'proto.me.world.usa.service.AutoCompleteResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.me.world.usa.service.AutoCompleteResponse.Item = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.me.world.usa.service.AutoCompleteResponse.Item.repeatedFields_, null);
};
goog.inherits(proto.me.world.usa.service.AutoCompleteResponse.Item, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.me.world.usa.service.AutoCompleteResponse.Item.displayName = 'proto.me.world.usa.service.AutoCompleteResponse.Item';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.me.world.usa.service.AutoCompleteResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.me.world.usa.service.AutoCompleteResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.me.world.usa.service.AutoCompleteResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.me.world.usa.service.AutoCompleteResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.me.world.usa.service.AutoCompleteResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    resultsList: jspb.Message.toObjectList(msg.getResultsList(),
    proto.me.world.usa.service.AutoCompleteResponse.Item.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.me.world.usa.service.AutoCompleteResponse}
 */
proto.me.world.usa.service.AutoCompleteResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.me.world.usa.service.AutoCompleteResponse;
  return proto.me.world.usa.service.AutoCompleteResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.me.world.usa.service.AutoCompleteResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.me.world.usa.service.AutoCompleteResponse}
 */
proto.me.world.usa.service.AutoCompleteResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.me.world.usa.service.AutoCompleteResponse.Item;
      reader.readMessage(value,proto.me.world.usa.service.AutoCompleteResponse.Item.deserializeBinaryFromReader);
      msg.addResults(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.me.world.usa.service.AutoCompleteResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.me.world.usa.service.AutoCompleteResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.me.world.usa.service.AutoCompleteResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.me.world.usa.service.AutoCompleteResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getResultsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.me.world.usa.service.AutoCompleteResponse.Item.serializeBinaryToWriter
    );
  }
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.me.world.usa.service.AutoCompleteResponse.Item.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.me.world.usa.service.AutoCompleteResponse.Item.prototype.toObject = function(opt_includeInstance) {
  return proto.me.world.usa.service.AutoCompleteResponse.Item.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.me.world.usa.service.AutoCompleteResponse.Item} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.me.world.usa.service.AutoCompleteResponse.Item.toObject = function(includeInstance, msg) {
  var f, obj = {
    url: jspb.Message.getFieldWithDefault(msg, 1, ""),
    title: jspb.Message.getFieldWithDefault(msg, 2, ""),
    snippetsList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.me.world.usa.service.AutoCompleteResponse.Item}
 */
proto.me.world.usa.service.AutoCompleteResponse.Item.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.me.world.usa.service.AutoCompleteResponse.Item;
  return proto.me.world.usa.service.AutoCompleteResponse.Item.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.me.world.usa.service.AutoCompleteResponse.Item} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.me.world.usa.service.AutoCompleteResponse.Item}
 */
proto.me.world.usa.service.AutoCompleteResponse.Item.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUrl(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addSnippets(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.me.world.usa.service.AutoCompleteResponse.Item.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.me.world.usa.service.AutoCompleteResponse.Item.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.me.world.usa.service.AutoCompleteResponse.Item} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.me.world.usa.service.AutoCompleteResponse.Item.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUrl();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getSnippetsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
};


/**
 * optional string url = 1;
 * @return {string}
 */
proto.me.world.usa.service.AutoCompleteResponse.Item.prototype.getUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.me.world.usa.service.AutoCompleteResponse.Item} returns this
 */
proto.me.world.usa.service.AutoCompleteResponse.Item.prototype.setUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string title = 2;
 * @return {string}
 */
proto.me.world.usa.service.AutoCompleteResponse.Item.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.me.world.usa.service.AutoCompleteResponse.Item} returns this
 */
proto.me.world.usa.service.AutoCompleteResponse.Item.prototype.setTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated string snippets = 3;
 * @return {!Array<string>}
 */
proto.me.world.usa.service.AutoCompleteResponse.Item.prototype.getSnippetsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.me.world.usa.service.AutoCompleteResponse.Item} returns this
 */
proto.me.world.usa.service.AutoCompleteResponse.Item.prototype.setSnippetsList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.me.world.usa.service.AutoCompleteResponse.Item} returns this
 */
proto.me.world.usa.service.AutoCompleteResponse.Item.prototype.addSnippets = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.me.world.usa.service.AutoCompleteResponse.Item} returns this
 */
proto.me.world.usa.service.AutoCompleteResponse.Item.prototype.clearSnippetsList = function() {
  return this.setSnippetsList([]);
};


/**
 * repeated Item results = 1;
 * @return {!Array<!proto.me.world.usa.service.AutoCompleteResponse.Item>}
 */
proto.me.world.usa.service.AutoCompleteResponse.prototype.getResultsList = function() {
  return /** @type{!Array<!proto.me.world.usa.service.AutoCompleteResponse.Item>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.me.world.usa.service.AutoCompleteResponse.Item, 1));
};


/**
 * @param {!Array<!proto.me.world.usa.service.AutoCompleteResponse.Item>} value
 * @return {!proto.me.world.usa.service.AutoCompleteResponse} returns this
*/
proto.me.world.usa.service.AutoCompleteResponse.prototype.setResultsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.me.world.usa.service.AutoCompleteResponse.Item=} opt_value
 * @param {number=} opt_index
 * @return {!proto.me.world.usa.service.AutoCompleteResponse.Item}
 */
proto.me.world.usa.service.AutoCompleteResponse.prototype.addResults = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.me.world.usa.service.AutoCompleteResponse.Item, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.me.world.usa.service.AutoCompleteResponse} returns this
 */
proto.me.world.usa.service.AutoCompleteResponse.prototype.clearResultsList = function() {
  return this.setResultsList([]);
};


goog.object.extend(exports, proto.me.world.usa.service);
