// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto

package me.world.base;

public final class Base {
  private Base() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:me.world.base.Date)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 day = 1;</code>
     * @return The day.
     */
    int getDay();

    /**
     * <code>int32 month = 2;</code>
     * @return The month.
     */
    int getMonth();

    /**
     * <code>int32 year = 3;</code>
     * @return The year.
     */
    int getYear();
  }
  /**
   * Protobuf type {@code me.world.base.Date}
   */
  public  static final class Date extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:me.world.base.Date)
      DateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Date.newBuilder() to construct.
    private Date(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Date() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Date();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Date(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              day_ = input.readInt32();
              break;
            }
            case 16: {

              month_ = input.readInt32();
              break;
            }
            case 24: {

              year_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.world.base.Base.internal_static_me_world_base_Date_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.world.base.Base.internal_static_me_world_base_Date_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.world.base.Base.Date.class, me.world.base.Base.Date.Builder.class);
    }

    public static final int DAY_FIELD_NUMBER = 1;
    private int day_;
    /**
     * <code>int32 day = 1;</code>
     * @return The day.
     */
    public int getDay() {
      return day_;
    }

    public static final int MONTH_FIELD_NUMBER = 2;
    private int month_;
    /**
     * <code>int32 month = 2;</code>
     * @return The month.
     */
    public int getMonth() {
      return month_;
    }

    public static final int YEAR_FIELD_NUMBER = 3;
    private int year_;
    /**
     * <code>int32 year = 3;</code>
     * @return The year.
     */
    public int getYear() {
      return year_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (day_ != 0) {
        output.writeInt32(1, day_);
      }
      if (month_ != 0) {
        output.writeInt32(2, month_);
      }
      if (year_ != 0) {
        output.writeInt32(3, year_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (day_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, day_);
      }
      if (month_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, month_);
      }
      if (year_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, year_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof me.world.base.Base.Date)) {
        return super.equals(obj);
      }
      me.world.base.Base.Date other = (me.world.base.Base.Date) obj;

      if (getDay()
          != other.getDay()) return false;
      if (getMonth()
          != other.getMonth()) return false;
      if (getYear()
          != other.getYear()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DAY_FIELD_NUMBER;
      hash = (53 * hash) + getDay();
      hash = (37 * hash) + MONTH_FIELD_NUMBER;
      hash = (53 * hash) + getMonth();
      hash = (37 * hash) + YEAR_FIELD_NUMBER;
      hash = (53 * hash) + getYear();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static me.world.base.Base.Date parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.world.base.Base.Date parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.world.base.Base.Date parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.world.base.Base.Date parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.world.base.Base.Date parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.world.base.Base.Date parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.world.base.Base.Date parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.world.base.Base.Date parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.world.base.Base.Date parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static me.world.base.Base.Date parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.world.base.Base.Date parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.world.base.Base.Date parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(me.world.base.Base.Date prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code me.world.base.Date}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:me.world.base.Date)
        me.world.base.Base.DateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.world.base.Base.internal_static_me_world_base_Date_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.world.base.Base.internal_static_me_world_base_Date_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.world.base.Base.Date.class, me.world.base.Base.Date.Builder.class);
      }

      // Construct using me.world.base.Base.Date.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        day_ = 0;

        month_ = 0;

        year_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.world.base.Base.internal_static_me_world_base_Date_descriptor;
      }

      @java.lang.Override
      public me.world.base.Base.Date getDefaultInstanceForType() {
        return me.world.base.Base.Date.getDefaultInstance();
      }

      @java.lang.Override
      public me.world.base.Base.Date build() {
        me.world.base.Base.Date result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public me.world.base.Base.Date buildPartial() {
        me.world.base.Base.Date result = new me.world.base.Base.Date(this);
        result.day_ = day_;
        result.month_ = month_;
        result.year_ = year_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.world.base.Base.Date) {
          return mergeFrom((me.world.base.Base.Date)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.world.base.Base.Date other) {
        if (other == me.world.base.Base.Date.getDefaultInstance()) return this;
        if (other.getDay() != 0) {
          setDay(other.getDay());
        }
        if (other.getMonth() != 0) {
          setMonth(other.getMonth());
        }
        if (other.getYear() != 0) {
          setYear(other.getYear());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        me.world.base.Base.Date parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (me.world.base.Base.Date) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int day_ ;
      /**
       * <code>int32 day = 1;</code>
       * @return The day.
       */
      public int getDay() {
        return day_;
      }
      /**
       * <code>int32 day = 1;</code>
       * @param value The day to set.
       * @return This builder for chaining.
       */
      public Builder setDay(int value) {
        
        day_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 day = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDay() {
        
        day_ = 0;
        onChanged();
        return this;
      }

      private int month_ ;
      /**
       * <code>int32 month = 2;</code>
       * @return The month.
       */
      public int getMonth() {
        return month_;
      }
      /**
       * <code>int32 month = 2;</code>
       * @param value The month to set.
       * @return This builder for chaining.
       */
      public Builder setMonth(int value) {
        
        month_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 month = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMonth() {
        
        month_ = 0;
        onChanged();
        return this;
      }

      private int year_ ;
      /**
       * <code>int32 year = 3;</code>
       * @return The year.
       */
      public int getYear() {
        return year_;
      }
      /**
       * <code>int32 year = 3;</code>
       * @param value The year to set.
       * @return This builder for chaining.
       */
      public Builder setYear(int value) {
        
        year_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 year = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearYear() {
        
        year_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:me.world.base.Date)
    }

    // @@protoc_insertion_point(class_scope:me.world.base.Date)
    private static final me.world.base.Base.Date DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new me.world.base.Base.Date();
    }

    public static me.world.base.Base.Date getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Date>
        PARSER = new com.google.protobuf.AbstractParser<Date>() {
      @java.lang.Override
      public Date parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Date(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Date> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Date> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public me.world.base.Base.Date getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TimeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:me.world.base.Time)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 hour = 1;</code>
     * @return The hour.
     */
    int getHour();

    /**
     * <code>int32 minute = 2;</code>
     * @return The minute.
     */
    int getMinute();

    /**
     * <code>int32 second = 3;</code>
     * @return The second.
     */
    int getSecond();
  }
  /**
   * Protobuf type {@code me.world.base.Time}
   */
  public  static final class Time extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:me.world.base.Time)
      TimeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Time.newBuilder() to construct.
    private Time(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Time() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Time();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Time(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              hour_ = input.readInt32();
              break;
            }
            case 16: {

              minute_ = input.readInt32();
              break;
            }
            case 24: {

              second_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.world.base.Base.internal_static_me_world_base_Time_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.world.base.Base.internal_static_me_world_base_Time_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.world.base.Base.Time.class, me.world.base.Base.Time.Builder.class);
    }

    public static final int HOUR_FIELD_NUMBER = 1;
    private int hour_;
    /**
     * <code>int32 hour = 1;</code>
     * @return The hour.
     */
    public int getHour() {
      return hour_;
    }

    public static final int MINUTE_FIELD_NUMBER = 2;
    private int minute_;
    /**
     * <code>int32 minute = 2;</code>
     * @return The minute.
     */
    public int getMinute() {
      return minute_;
    }

    public static final int SECOND_FIELD_NUMBER = 3;
    private int second_;
    /**
     * <code>int32 second = 3;</code>
     * @return The second.
     */
    public int getSecond() {
      return second_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hour_ != 0) {
        output.writeInt32(1, hour_);
      }
      if (minute_ != 0) {
        output.writeInt32(2, minute_);
      }
      if (second_ != 0) {
        output.writeInt32(3, second_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (hour_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, hour_);
      }
      if (minute_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, minute_);
      }
      if (second_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, second_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof me.world.base.Base.Time)) {
        return super.equals(obj);
      }
      me.world.base.Base.Time other = (me.world.base.Base.Time) obj;

      if (getHour()
          != other.getHour()) return false;
      if (getMinute()
          != other.getMinute()) return false;
      if (getSecond()
          != other.getSecond()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HOUR_FIELD_NUMBER;
      hash = (53 * hash) + getHour();
      hash = (37 * hash) + MINUTE_FIELD_NUMBER;
      hash = (53 * hash) + getMinute();
      hash = (37 * hash) + SECOND_FIELD_NUMBER;
      hash = (53 * hash) + getSecond();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static me.world.base.Base.Time parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.world.base.Base.Time parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.world.base.Base.Time parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.world.base.Base.Time parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.world.base.Base.Time parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.world.base.Base.Time parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.world.base.Base.Time parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.world.base.Base.Time parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.world.base.Base.Time parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static me.world.base.Base.Time parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.world.base.Base.Time parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.world.base.Base.Time parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(me.world.base.Base.Time prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code me.world.base.Time}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:me.world.base.Time)
        me.world.base.Base.TimeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.world.base.Base.internal_static_me_world_base_Time_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.world.base.Base.internal_static_me_world_base_Time_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.world.base.Base.Time.class, me.world.base.Base.Time.Builder.class);
      }

      // Construct using me.world.base.Base.Time.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        hour_ = 0;

        minute_ = 0;

        second_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.world.base.Base.internal_static_me_world_base_Time_descriptor;
      }

      @java.lang.Override
      public me.world.base.Base.Time getDefaultInstanceForType() {
        return me.world.base.Base.Time.getDefaultInstance();
      }

      @java.lang.Override
      public me.world.base.Base.Time build() {
        me.world.base.Base.Time result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public me.world.base.Base.Time buildPartial() {
        me.world.base.Base.Time result = new me.world.base.Base.Time(this);
        result.hour_ = hour_;
        result.minute_ = minute_;
        result.second_ = second_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.world.base.Base.Time) {
          return mergeFrom((me.world.base.Base.Time)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.world.base.Base.Time other) {
        if (other == me.world.base.Base.Time.getDefaultInstance()) return this;
        if (other.getHour() != 0) {
          setHour(other.getHour());
        }
        if (other.getMinute() != 0) {
          setMinute(other.getMinute());
        }
        if (other.getSecond() != 0) {
          setSecond(other.getSecond());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        me.world.base.Base.Time parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (me.world.base.Base.Time) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int hour_ ;
      /**
       * <code>int32 hour = 1;</code>
       * @return The hour.
       */
      public int getHour() {
        return hour_;
      }
      /**
       * <code>int32 hour = 1;</code>
       * @param value The hour to set.
       * @return This builder for chaining.
       */
      public Builder setHour(int value) {
        
        hour_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 hour = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearHour() {
        
        hour_ = 0;
        onChanged();
        return this;
      }

      private int minute_ ;
      /**
       * <code>int32 minute = 2;</code>
       * @return The minute.
       */
      public int getMinute() {
        return minute_;
      }
      /**
       * <code>int32 minute = 2;</code>
       * @param value The minute to set.
       * @return This builder for chaining.
       */
      public Builder setMinute(int value) {
        
        minute_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 minute = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMinute() {
        
        minute_ = 0;
        onChanged();
        return this;
      }

      private int second_ ;
      /**
       * <code>int32 second = 3;</code>
       * @return The second.
       */
      public int getSecond() {
        return second_;
      }
      /**
       * <code>int32 second = 3;</code>
       * @param value The second to set.
       * @return This builder for chaining.
       */
      public Builder setSecond(int value) {
        
        second_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 second = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSecond() {
        
        second_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:me.world.base.Time)
    }

    // @@protoc_insertion_point(class_scope:me.world.base.Time)
    private static final me.world.base.Base.Time DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new me.world.base.Base.Time();
    }

    public static me.world.base.Base.Time getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Time>
        PARSER = new com.google.protobuf.AbstractParser<Time>() {
      @java.lang.Override
      public Time parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Time(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Time> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Time> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public me.world.base.Base.Time getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DateTimeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:me.world.base.DateTime)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 day = 1;</code>
     * @return The day.
     */
    int getDay();

    /**
     * <code>int32 month = 2;</code>
     * @return The month.
     */
    int getMonth();

    /**
     * <code>int32 year = 3;</code>
     * @return The year.
     */
    int getYear();

    /**
     * <code>int32 hour = 4;</code>
     * @return The hour.
     */
    int getHour();

    /**
     * <code>int32 minute = 5;</code>
     * @return The minute.
     */
    int getMinute();

    /**
     * <code>int32 second = 6;</code>
     * @return The second.
     */
    int getSecond();
  }
  /**
   * Protobuf type {@code me.world.base.DateTime}
   */
  public  static final class DateTime extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:me.world.base.DateTime)
      DateTimeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DateTime.newBuilder() to construct.
    private DateTime(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DateTime() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DateTime();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DateTime(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              day_ = input.readInt32();
              break;
            }
            case 16: {

              month_ = input.readInt32();
              break;
            }
            case 24: {

              year_ = input.readInt32();
              break;
            }
            case 32: {

              hour_ = input.readInt32();
              break;
            }
            case 40: {

              minute_ = input.readInt32();
              break;
            }
            case 48: {

              second_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.world.base.Base.internal_static_me_world_base_DateTime_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.world.base.Base.internal_static_me_world_base_DateTime_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.world.base.Base.DateTime.class, me.world.base.Base.DateTime.Builder.class);
    }

    public static final int DAY_FIELD_NUMBER = 1;
    private int day_;
    /**
     * <code>int32 day = 1;</code>
     * @return The day.
     */
    public int getDay() {
      return day_;
    }

    public static final int MONTH_FIELD_NUMBER = 2;
    private int month_;
    /**
     * <code>int32 month = 2;</code>
     * @return The month.
     */
    public int getMonth() {
      return month_;
    }

    public static final int YEAR_FIELD_NUMBER = 3;
    private int year_;
    /**
     * <code>int32 year = 3;</code>
     * @return The year.
     */
    public int getYear() {
      return year_;
    }

    public static final int HOUR_FIELD_NUMBER = 4;
    private int hour_;
    /**
     * <code>int32 hour = 4;</code>
     * @return The hour.
     */
    public int getHour() {
      return hour_;
    }

    public static final int MINUTE_FIELD_NUMBER = 5;
    private int minute_;
    /**
     * <code>int32 minute = 5;</code>
     * @return The minute.
     */
    public int getMinute() {
      return minute_;
    }

    public static final int SECOND_FIELD_NUMBER = 6;
    private int second_;
    /**
     * <code>int32 second = 6;</code>
     * @return The second.
     */
    public int getSecond() {
      return second_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (day_ != 0) {
        output.writeInt32(1, day_);
      }
      if (month_ != 0) {
        output.writeInt32(2, month_);
      }
      if (year_ != 0) {
        output.writeInt32(3, year_);
      }
      if (hour_ != 0) {
        output.writeInt32(4, hour_);
      }
      if (minute_ != 0) {
        output.writeInt32(5, minute_);
      }
      if (second_ != 0) {
        output.writeInt32(6, second_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (day_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, day_);
      }
      if (month_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, month_);
      }
      if (year_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, year_);
      }
      if (hour_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, hour_);
      }
      if (minute_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, minute_);
      }
      if (second_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, second_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof me.world.base.Base.DateTime)) {
        return super.equals(obj);
      }
      me.world.base.Base.DateTime other = (me.world.base.Base.DateTime) obj;

      if (getDay()
          != other.getDay()) return false;
      if (getMonth()
          != other.getMonth()) return false;
      if (getYear()
          != other.getYear()) return false;
      if (getHour()
          != other.getHour()) return false;
      if (getMinute()
          != other.getMinute()) return false;
      if (getSecond()
          != other.getSecond()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DAY_FIELD_NUMBER;
      hash = (53 * hash) + getDay();
      hash = (37 * hash) + MONTH_FIELD_NUMBER;
      hash = (53 * hash) + getMonth();
      hash = (37 * hash) + YEAR_FIELD_NUMBER;
      hash = (53 * hash) + getYear();
      hash = (37 * hash) + HOUR_FIELD_NUMBER;
      hash = (53 * hash) + getHour();
      hash = (37 * hash) + MINUTE_FIELD_NUMBER;
      hash = (53 * hash) + getMinute();
      hash = (37 * hash) + SECOND_FIELD_NUMBER;
      hash = (53 * hash) + getSecond();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static me.world.base.Base.DateTime parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.world.base.Base.DateTime parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.world.base.Base.DateTime parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.world.base.Base.DateTime parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.world.base.Base.DateTime parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.world.base.Base.DateTime parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.world.base.Base.DateTime parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.world.base.Base.DateTime parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.world.base.Base.DateTime parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static me.world.base.Base.DateTime parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.world.base.Base.DateTime parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.world.base.Base.DateTime parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(me.world.base.Base.DateTime prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code me.world.base.DateTime}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:me.world.base.DateTime)
        me.world.base.Base.DateTimeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.world.base.Base.internal_static_me_world_base_DateTime_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.world.base.Base.internal_static_me_world_base_DateTime_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.world.base.Base.DateTime.class, me.world.base.Base.DateTime.Builder.class);
      }

      // Construct using me.world.base.Base.DateTime.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        day_ = 0;

        month_ = 0;

        year_ = 0;

        hour_ = 0;

        minute_ = 0;

        second_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.world.base.Base.internal_static_me_world_base_DateTime_descriptor;
      }

      @java.lang.Override
      public me.world.base.Base.DateTime getDefaultInstanceForType() {
        return me.world.base.Base.DateTime.getDefaultInstance();
      }

      @java.lang.Override
      public me.world.base.Base.DateTime build() {
        me.world.base.Base.DateTime result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public me.world.base.Base.DateTime buildPartial() {
        me.world.base.Base.DateTime result = new me.world.base.Base.DateTime(this);
        result.day_ = day_;
        result.month_ = month_;
        result.year_ = year_;
        result.hour_ = hour_;
        result.minute_ = minute_;
        result.second_ = second_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.world.base.Base.DateTime) {
          return mergeFrom((me.world.base.Base.DateTime)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.world.base.Base.DateTime other) {
        if (other == me.world.base.Base.DateTime.getDefaultInstance()) return this;
        if (other.getDay() != 0) {
          setDay(other.getDay());
        }
        if (other.getMonth() != 0) {
          setMonth(other.getMonth());
        }
        if (other.getYear() != 0) {
          setYear(other.getYear());
        }
        if (other.getHour() != 0) {
          setHour(other.getHour());
        }
        if (other.getMinute() != 0) {
          setMinute(other.getMinute());
        }
        if (other.getSecond() != 0) {
          setSecond(other.getSecond());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        me.world.base.Base.DateTime parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (me.world.base.Base.DateTime) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int day_ ;
      /**
       * <code>int32 day = 1;</code>
       * @return The day.
       */
      public int getDay() {
        return day_;
      }
      /**
       * <code>int32 day = 1;</code>
       * @param value The day to set.
       * @return This builder for chaining.
       */
      public Builder setDay(int value) {
        
        day_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 day = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDay() {
        
        day_ = 0;
        onChanged();
        return this;
      }

      private int month_ ;
      /**
       * <code>int32 month = 2;</code>
       * @return The month.
       */
      public int getMonth() {
        return month_;
      }
      /**
       * <code>int32 month = 2;</code>
       * @param value The month to set.
       * @return This builder for chaining.
       */
      public Builder setMonth(int value) {
        
        month_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 month = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMonth() {
        
        month_ = 0;
        onChanged();
        return this;
      }

      private int year_ ;
      /**
       * <code>int32 year = 3;</code>
       * @return The year.
       */
      public int getYear() {
        return year_;
      }
      /**
       * <code>int32 year = 3;</code>
       * @param value The year to set.
       * @return This builder for chaining.
       */
      public Builder setYear(int value) {
        
        year_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 year = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearYear() {
        
        year_ = 0;
        onChanged();
        return this;
      }

      private int hour_ ;
      /**
       * <code>int32 hour = 4;</code>
       * @return The hour.
       */
      public int getHour() {
        return hour_;
      }
      /**
       * <code>int32 hour = 4;</code>
       * @param value The hour to set.
       * @return This builder for chaining.
       */
      public Builder setHour(int value) {
        
        hour_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 hour = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearHour() {
        
        hour_ = 0;
        onChanged();
        return this;
      }

      private int minute_ ;
      /**
       * <code>int32 minute = 5;</code>
       * @return The minute.
       */
      public int getMinute() {
        return minute_;
      }
      /**
       * <code>int32 minute = 5;</code>
       * @param value The minute to set.
       * @return This builder for chaining.
       */
      public Builder setMinute(int value) {
        
        minute_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 minute = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearMinute() {
        
        minute_ = 0;
        onChanged();
        return this;
      }

      private int second_ ;
      /**
       * <code>int32 second = 6;</code>
       * @return The second.
       */
      public int getSecond() {
        return second_;
      }
      /**
       * <code>int32 second = 6;</code>
       * @param value The second to set.
       * @return This builder for chaining.
       */
      public Builder setSecond(int value) {
        
        second_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 second = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearSecond() {
        
        second_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:me.world.base.DateTime)
    }

    // @@protoc_insertion_point(class_scope:me.world.base.DateTime)
    private static final me.world.base.Base.DateTime DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new me.world.base.Base.DateTime();
    }

    public static me.world.base.Base.DateTime getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DateTime>
        PARSER = new com.google.protobuf.AbstractParser<DateTime>() {
      @java.lang.Override
      public DateTime parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DateTime(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DateTime> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DateTime> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public me.world.base.Base.DateTime getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_world_base_Date_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_world_base_Date_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_world_base_Time_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_world_base_Time_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_world_base_DateTime_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_world_base_DateTime_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nbase.proto\022\rme.world.base\"0\n\004Date\022\013\n\003d" +
      "ay\030\001 \001(\005\022\r\n\005month\030\002 \001(\005\022\014\n\004year\030\003 \001(\005\"4\n" +
      "\004Time\022\014\n\004hour\030\001 \001(\005\022\016\n\006minute\030\002 \001(\005\022\016\n\006s" +
      "econd\030\003 \001(\005\"b\n\010DateTime\022\013\n\003day\030\001 \001(\005\022\r\n\005" +
      "month\030\002 \001(\005\022\014\n\004year\030\003 \001(\005\022\014\n\004hour\030\004 \001(\005\022" +
      "\016\n\006minute\030\005 \001(\005\022\016\n\006second\030\006 \001(\005b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_me_world_base_Date_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_me_world_base_Date_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_world_base_Date_descriptor,
        new java.lang.String[] { "Day", "Month", "Year", });
    internal_static_me_world_base_Time_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_me_world_base_Time_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_world_base_Time_descriptor,
        new java.lang.String[] { "Hour", "Minute", "Second", });
    internal_static_me_world_base_DateTime_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_me_world_base_DateTime_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_world_base_DateTime_descriptor,
        new java.lang.String[] { "Day", "Month", "Year", "Hour", "Minute", "Second", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
