// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: autocomplete.proto

package me.world.usa.service;

public final class Autocomplete {
  private Autocomplete() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AutoCompleteResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:me.world.usa.service.AutoCompleteResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .me.world.usa.service.AutoCompleteResponse.Item results = 1;</code>
     */
    java.util.List<me.world.usa.service.Autocomplete.AutoCompleteResponse.Item> 
        getResultsList();
    /**
     * <code>repeated .me.world.usa.service.AutoCompleteResponse.Item results = 1;</code>
     */
    me.world.usa.service.Autocomplete.AutoCompleteResponse.Item getResults(int index);
    /**
     * <code>repeated .me.world.usa.service.AutoCompleteResponse.Item results = 1;</code>
     */
    int getResultsCount();
    /**
     * <code>repeated .me.world.usa.service.AutoCompleteResponse.Item results = 1;</code>
     */
    java.util.List<? extends me.world.usa.service.Autocomplete.AutoCompleteResponse.ItemOrBuilder> 
        getResultsOrBuilderList();
    /**
     * <code>repeated .me.world.usa.service.AutoCompleteResponse.Item results = 1;</code>
     */
    me.world.usa.service.Autocomplete.AutoCompleteResponse.ItemOrBuilder getResultsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code me.world.usa.service.AutoCompleteResponse}
   */
  public  static final class AutoCompleteResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:me.world.usa.service.AutoCompleteResponse)
      AutoCompleteResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AutoCompleteResponse.newBuilder() to construct.
    private AutoCompleteResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AutoCompleteResponse() {
      results_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AutoCompleteResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AutoCompleteResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                results_ = new java.util.ArrayList<me.world.usa.service.Autocomplete.AutoCompleteResponse.Item>();
                mutable_bitField0_ |= 0x00000001;
              }
              results_.add(
                  input.readMessage(me.world.usa.service.Autocomplete.AutoCompleteResponse.Item.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          results_ = java.util.Collections.unmodifiableList(results_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.world.usa.service.Autocomplete.internal_static_me_world_usa_service_AutoCompleteResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.world.usa.service.Autocomplete.internal_static_me_world_usa_service_AutoCompleteResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.world.usa.service.Autocomplete.AutoCompleteResponse.class, me.world.usa.service.Autocomplete.AutoCompleteResponse.Builder.class);
    }

    public interface ItemOrBuilder extends
        // @@protoc_insertion_point(interface_extends:me.world.usa.service.AutoCompleteResponse.Item)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string url = 1;</code>
       * @return The url.
       */
      java.lang.String getUrl();
      /**
       * <code>string url = 1;</code>
       * @return The bytes for url.
       */
      com.google.protobuf.ByteString
          getUrlBytes();

      /**
       * <code>string title = 2;</code>
       * @return The title.
       */
      java.lang.String getTitle();
      /**
       * <code>string title = 2;</code>
       * @return The bytes for title.
       */
      com.google.protobuf.ByteString
          getTitleBytes();

      /**
       * <code>repeated string snippets = 3;</code>
       * @return A list containing the snippets.
       */
      java.util.List<java.lang.String>
          getSnippetsList();
      /**
       * <code>repeated string snippets = 3;</code>
       * @return The count of snippets.
       */
      int getSnippetsCount();
      /**
       * <code>repeated string snippets = 3;</code>
       * @param index The index of the element to return.
       * @return The snippets at the given index.
       */
      java.lang.String getSnippets(int index);
      /**
       * <code>repeated string snippets = 3;</code>
       * @param index The index of the value to return.
       * @return The bytes of the snippets at the given index.
       */
      com.google.protobuf.ByteString
          getSnippetsBytes(int index);
    }
    /**
     * Protobuf type {@code me.world.usa.service.AutoCompleteResponse.Item}
     */
    public  static final class Item extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:me.world.usa.service.AutoCompleteResponse.Item)
        ItemOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Item.newBuilder() to construct.
      private Item(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Item() {
        url_ = "";
        title_ = "";
        snippets_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Item();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Item(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                url_ = s;
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                title_ = s;
                break;
              }
              case 26: {
                java.lang.String s = input.readStringRequireUtf8();
                if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                  snippets_ = new com.google.protobuf.LazyStringArrayList();
                  mutable_bitField0_ |= 0x00000001;
                }
                snippets_.add(s);
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000001) != 0)) {
            snippets_ = snippets_.getUnmodifiableView();
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.world.usa.service.Autocomplete.internal_static_me_world_usa_service_AutoCompleteResponse_Item_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.world.usa.service.Autocomplete.internal_static_me_world_usa_service_AutoCompleteResponse_Item_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.world.usa.service.Autocomplete.AutoCompleteResponse.Item.class, me.world.usa.service.Autocomplete.AutoCompleteResponse.Item.Builder.class);
      }

      public static final int URL_FIELD_NUMBER = 1;
      private volatile java.lang.Object url_;
      /**
       * <code>string url = 1;</code>
       * @return The url.
       */
      public java.lang.String getUrl() {
        java.lang.Object ref = url_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          url_ = s;
          return s;
        }
      }
      /**
       * <code>string url = 1;</code>
       * @return The bytes for url.
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        java.lang.Object ref = url_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int TITLE_FIELD_NUMBER = 2;
      private volatile java.lang.Object title_;
      /**
       * <code>string title = 2;</code>
       * @return The title.
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        }
      }
      /**
       * <code>string title = 2;</code>
       * @return The bytes for title.
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int SNIPPETS_FIELD_NUMBER = 3;
      private com.google.protobuf.LazyStringList snippets_;
      /**
       * <code>repeated string snippets = 3;</code>
       * @return A list containing the snippets.
       */
      public com.google.protobuf.ProtocolStringList
          getSnippetsList() {
        return snippets_;
      }
      /**
       * <code>repeated string snippets = 3;</code>
       * @return The count of snippets.
       */
      public int getSnippetsCount() {
        return snippets_.size();
      }
      /**
       * <code>repeated string snippets = 3;</code>
       * @param index The index of the element to return.
       * @return The snippets at the given index.
       */
      public java.lang.String getSnippets(int index) {
        return snippets_.get(index);
      }
      /**
       * <code>repeated string snippets = 3;</code>
       * @param index The index of the value to return.
       * @return The bytes of the snippets at the given index.
       */
      public com.google.protobuf.ByteString
          getSnippetsBytes(int index) {
        return snippets_.getByteString(index);
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getUrlBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, url_);
        }
        if (!getTitleBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
        }
        for (int i = 0; i < snippets_.size(); i++) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, snippets_.getRaw(i));
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getUrlBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, url_);
        }
        if (!getTitleBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
        }
        {
          int dataSize = 0;
          for (int i = 0; i < snippets_.size(); i++) {
            dataSize += computeStringSizeNoTag(snippets_.getRaw(i));
          }
          size += dataSize;
          size += 1 * getSnippetsList().size();
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof me.world.usa.service.Autocomplete.AutoCompleteResponse.Item)) {
          return super.equals(obj);
        }
        me.world.usa.service.Autocomplete.AutoCompleteResponse.Item other = (me.world.usa.service.Autocomplete.AutoCompleteResponse.Item) obj;

        if (!getUrl()
            .equals(other.getUrl())) return false;
        if (!getTitle()
            .equals(other.getTitle())) return false;
        if (!getSnippetsList()
            .equals(other.getSnippetsList())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + URL_FIELD_NUMBER;
        hash = (53 * hash) + getUrl().hashCode();
        hash = (37 * hash) + TITLE_FIELD_NUMBER;
        hash = (53 * hash) + getTitle().hashCode();
        if (getSnippetsCount() > 0) {
          hash = (37 * hash) + SNIPPETS_FIELD_NUMBER;
          hash = (53 * hash) + getSnippetsList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static me.world.usa.service.Autocomplete.AutoCompleteResponse.Item parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static me.world.usa.service.Autocomplete.AutoCompleteResponse.Item parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static me.world.usa.service.Autocomplete.AutoCompleteResponse.Item parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static me.world.usa.service.Autocomplete.AutoCompleteResponse.Item parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static me.world.usa.service.Autocomplete.AutoCompleteResponse.Item parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static me.world.usa.service.Autocomplete.AutoCompleteResponse.Item parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static me.world.usa.service.Autocomplete.AutoCompleteResponse.Item parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static me.world.usa.service.Autocomplete.AutoCompleteResponse.Item parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static me.world.usa.service.Autocomplete.AutoCompleteResponse.Item parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static me.world.usa.service.Autocomplete.AutoCompleteResponse.Item parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static me.world.usa.service.Autocomplete.AutoCompleteResponse.Item parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static me.world.usa.service.Autocomplete.AutoCompleteResponse.Item parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(me.world.usa.service.Autocomplete.AutoCompleteResponse.Item prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code me.world.usa.service.AutoCompleteResponse.Item}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:me.world.usa.service.AutoCompleteResponse.Item)
          me.world.usa.service.Autocomplete.AutoCompleteResponse.ItemOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return me.world.usa.service.Autocomplete.internal_static_me_world_usa_service_AutoCompleteResponse_Item_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return me.world.usa.service.Autocomplete.internal_static_me_world_usa_service_AutoCompleteResponse_Item_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  me.world.usa.service.Autocomplete.AutoCompleteResponse.Item.class, me.world.usa.service.Autocomplete.AutoCompleteResponse.Item.Builder.class);
        }

        // Construct using me.world.usa.service.Autocomplete.AutoCompleteResponse.Item.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          url_ = "";

          title_ = "";

          snippets_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return me.world.usa.service.Autocomplete.internal_static_me_world_usa_service_AutoCompleteResponse_Item_descriptor;
        }

        @java.lang.Override
        public me.world.usa.service.Autocomplete.AutoCompleteResponse.Item getDefaultInstanceForType() {
          return me.world.usa.service.Autocomplete.AutoCompleteResponse.Item.getDefaultInstance();
        }

        @java.lang.Override
        public me.world.usa.service.Autocomplete.AutoCompleteResponse.Item build() {
          me.world.usa.service.Autocomplete.AutoCompleteResponse.Item result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public me.world.usa.service.Autocomplete.AutoCompleteResponse.Item buildPartial() {
          me.world.usa.service.Autocomplete.AutoCompleteResponse.Item result = new me.world.usa.service.Autocomplete.AutoCompleteResponse.Item(this);
          int from_bitField0_ = bitField0_;
          result.url_ = url_;
          result.title_ = title_;
          if (((bitField0_ & 0x00000001) != 0)) {
            snippets_ = snippets_.getUnmodifiableView();
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.snippets_ = snippets_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof me.world.usa.service.Autocomplete.AutoCompleteResponse.Item) {
            return mergeFrom((me.world.usa.service.Autocomplete.AutoCompleteResponse.Item)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(me.world.usa.service.Autocomplete.AutoCompleteResponse.Item other) {
          if (other == me.world.usa.service.Autocomplete.AutoCompleteResponse.Item.getDefaultInstance()) return this;
          if (!other.getUrl().isEmpty()) {
            url_ = other.url_;
            onChanged();
          }
          if (!other.getTitle().isEmpty()) {
            title_ = other.title_;
            onChanged();
          }
          if (!other.snippets_.isEmpty()) {
            if (snippets_.isEmpty()) {
              snippets_ = other.snippets_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSnippetsIsMutable();
              snippets_.addAll(other.snippets_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          me.world.usa.service.Autocomplete.AutoCompleteResponse.Item parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (me.world.usa.service.Autocomplete.AutoCompleteResponse.Item) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object url_ = "";
        /**
         * <code>string url = 1;</code>
         * @return The url.
         */
        public java.lang.String getUrl() {
          java.lang.Object ref = url_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            url_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string url = 1;</code>
         * @return The bytes for url.
         */
        public com.google.protobuf.ByteString
            getUrlBytes() {
          java.lang.Object ref = url_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            url_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string url = 1;</code>
         * @param value The url to set.
         * @return This builder for chaining.
         */
        public Builder setUrl(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          url_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string url = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearUrl() {
          
          url_ = getDefaultInstance().getUrl();
          onChanged();
          return this;
        }
        /**
         * <code>string url = 1;</code>
         * @param value The bytes for url to set.
         * @return This builder for chaining.
         */
        public Builder setUrlBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          url_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object title_ = "";
        /**
         * <code>string title = 2;</code>
         * @return The title.
         */
        public java.lang.String getTitle() {
          java.lang.Object ref = title_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            title_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string title = 2;</code>
         * @return The bytes for title.
         */
        public com.google.protobuf.ByteString
            getTitleBytes() {
          java.lang.Object ref = title_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            title_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string title = 2;</code>
         * @param value The title to set.
         * @return This builder for chaining.
         */
        public Builder setTitle(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          title_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string title = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearTitle() {
          
          title_ = getDefaultInstance().getTitle();
          onChanged();
          return this;
        }
        /**
         * <code>string title = 2;</code>
         * @param value The bytes for title to set.
         * @return This builder for chaining.
         */
        public Builder setTitleBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          title_ = value;
          onChanged();
          return this;
        }

        private com.google.protobuf.LazyStringList snippets_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        private void ensureSnippetsIsMutable() {
          if (!((bitField0_ & 0x00000001) != 0)) {
            snippets_ = new com.google.protobuf.LazyStringArrayList(snippets_);
            bitField0_ |= 0x00000001;
           }
        }
        /**
         * <code>repeated string snippets = 3;</code>
         * @return A list containing the snippets.
         */
        public com.google.protobuf.ProtocolStringList
            getSnippetsList() {
          return snippets_.getUnmodifiableView();
        }
        /**
         * <code>repeated string snippets = 3;</code>
         * @return The count of snippets.
         */
        public int getSnippetsCount() {
          return snippets_.size();
        }
        /**
         * <code>repeated string snippets = 3;</code>
         * @param index The index of the element to return.
         * @return The snippets at the given index.
         */
        public java.lang.String getSnippets(int index) {
          return snippets_.get(index);
        }
        /**
         * <code>repeated string snippets = 3;</code>
         * @param index The index of the value to return.
         * @return The bytes of the snippets at the given index.
         */
        public com.google.protobuf.ByteString
            getSnippetsBytes(int index) {
          return snippets_.getByteString(index);
        }
        /**
         * <code>repeated string snippets = 3;</code>
         * @param index The index to set the value at.
         * @param value The snippets to set.
         * @return This builder for chaining.
         */
        public Builder setSnippets(
            int index, java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureSnippetsIsMutable();
          snippets_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string snippets = 3;</code>
         * @param value The snippets to add.
         * @return This builder for chaining.
         */
        public Builder addSnippets(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureSnippetsIsMutable();
          snippets_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string snippets = 3;</code>
         * @param values The snippets to add.
         * @return This builder for chaining.
         */
        public Builder addAllSnippets(
            java.lang.Iterable<java.lang.String> values) {
          ensureSnippetsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, snippets_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string snippets = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearSnippets() {
          snippets_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string snippets = 3;</code>
         * @param value The bytes of the snippets to add.
         * @return This builder for chaining.
         */
        public Builder addSnippetsBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          ensureSnippetsIsMutable();
          snippets_.add(value);
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:me.world.usa.service.AutoCompleteResponse.Item)
      }

      // @@protoc_insertion_point(class_scope:me.world.usa.service.AutoCompleteResponse.Item)
      private static final me.world.usa.service.Autocomplete.AutoCompleteResponse.Item DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new me.world.usa.service.Autocomplete.AutoCompleteResponse.Item();
      }

      public static me.world.usa.service.Autocomplete.AutoCompleteResponse.Item getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Item>
          PARSER = new com.google.protobuf.AbstractParser<Item>() {
        @java.lang.Override
        public Item parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Item(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Item> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Item> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public me.world.usa.service.Autocomplete.AutoCompleteResponse.Item getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int RESULTS_FIELD_NUMBER = 1;
    private java.util.List<me.world.usa.service.Autocomplete.AutoCompleteResponse.Item> results_;
    /**
     * <code>repeated .me.world.usa.service.AutoCompleteResponse.Item results = 1;</code>
     */
    public java.util.List<me.world.usa.service.Autocomplete.AutoCompleteResponse.Item> getResultsList() {
      return results_;
    }
    /**
     * <code>repeated .me.world.usa.service.AutoCompleteResponse.Item results = 1;</code>
     */
    public java.util.List<? extends me.world.usa.service.Autocomplete.AutoCompleteResponse.ItemOrBuilder> 
        getResultsOrBuilderList() {
      return results_;
    }
    /**
     * <code>repeated .me.world.usa.service.AutoCompleteResponse.Item results = 1;</code>
     */
    public int getResultsCount() {
      return results_.size();
    }
    /**
     * <code>repeated .me.world.usa.service.AutoCompleteResponse.Item results = 1;</code>
     */
    public me.world.usa.service.Autocomplete.AutoCompleteResponse.Item getResults(int index) {
      return results_.get(index);
    }
    /**
     * <code>repeated .me.world.usa.service.AutoCompleteResponse.Item results = 1;</code>
     */
    public me.world.usa.service.Autocomplete.AutoCompleteResponse.ItemOrBuilder getResultsOrBuilder(
        int index) {
      return results_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < results_.size(); i++) {
        output.writeMessage(1, results_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < results_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, results_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof me.world.usa.service.Autocomplete.AutoCompleteResponse)) {
        return super.equals(obj);
      }
      me.world.usa.service.Autocomplete.AutoCompleteResponse other = (me.world.usa.service.Autocomplete.AutoCompleteResponse) obj;

      if (!getResultsList()
          .equals(other.getResultsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getResultsCount() > 0) {
        hash = (37 * hash) + RESULTS_FIELD_NUMBER;
        hash = (53 * hash) + getResultsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static me.world.usa.service.Autocomplete.AutoCompleteResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.world.usa.service.Autocomplete.AutoCompleteResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.world.usa.service.Autocomplete.AutoCompleteResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.world.usa.service.Autocomplete.AutoCompleteResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.world.usa.service.Autocomplete.AutoCompleteResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.world.usa.service.Autocomplete.AutoCompleteResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.world.usa.service.Autocomplete.AutoCompleteResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.world.usa.service.Autocomplete.AutoCompleteResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.world.usa.service.Autocomplete.AutoCompleteResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static me.world.usa.service.Autocomplete.AutoCompleteResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.world.usa.service.Autocomplete.AutoCompleteResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.world.usa.service.Autocomplete.AutoCompleteResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(me.world.usa.service.Autocomplete.AutoCompleteResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code me.world.usa.service.AutoCompleteResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:me.world.usa.service.AutoCompleteResponse)
        me.world.usa.service.Autocomplete.AutoCompleteResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.world.usa.service.Autocomplete.internal_static_me_world_usa_service_AutoCompleteResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.world.usa.service.Autocomplete.internal_static_me_world_usa_service_AutoCompleteResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.world.usa.service.Autocomplete.AutoCompleteResponse.class, me.world.usa.service.Autocomplete.AutoCompleteResponse.Builder.class);
      }

      // Construct using me.world.usa.service.Autocomplete.AutoCompleteResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getResultsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (resultsBuilder_ == null) {
          results_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          resultsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.world.usa.service.Autocomplete.internal_static_me_world_usa_service_AutoCompleteResponse_descriptor;
      }

      @java.lang.Override
      public me.world.usa.service.Autocomplete.AutoCompleteResponse getDefaultInstanceForType() {
        return me.world.usa.service.Autocomplete.AutoCompleteResponse.getDefaultInstance();
      }

      @java.lang.Override
      public me.world.usa.service.Autocomplete.AutoCompleteResponse build() {
        me.world.usa.service.Autocomplete.AutoCompleteResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public me.world.usa.service.Autocomplete.AutoCompleteResponse buildPartial() {
        me.world.usa.service.Autocomplete.AutoCompleteResponse result = new me.world.usa.service.Autocomplete.AutoCompleteResponse(this);
        int from_bitField0_ = bitField0_;
        if (resultsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            results_ = java.util.Collections.unmodifiableList(results_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.results_ = results_;
        } else {
          result.results_ = resultsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.world.usa.service.Autocomplete.AutoCompleteResponse) {
          return mergeFrom((me.world.usa.service.Autocomplete.AutoCompleteResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.world.usa.service.Autocomplete.AutoCompleteResponse other) {
        if (other == me.world.usa.service.Autocomplete.AutoCompleteResponse.getDefaultInstance()) return this;
        if (resultsBuilder_ == null) {
          if (!other.results_.isEmpty()) {
            if (results_.isEmpty()) {
              results_ = other.results_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureResultsIsMutable();
              results_.addAll(other.results_);
            }
            onChanged();
          }
        } else {
          if (!other.results_.isEmpty()) {
            if (resultsBuilder_.isEmpty()) {
              resultsBuilder_.dispose();
              resultsBuilder_ = null;
              results_ = other.results_;
              bitField0_ = (bitField0_ & ~0x00000001);
              resultsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getResultsFieldBuilder() : null;
            } else {
              resultsBuilder_.addAllMessages(other.results_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        me.world.usa.service.Autocomplete.AutoCompleteResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (me.world.usa.service.Autocomplete.AutoCompleteResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<me.world.usa.service.Autocomplete.AutoCompleteResponse.Item> results_ =
        java.util.Collections.emptyList();
      private void ensureResultsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          results_ = new java.util.ArrayList<me.world.usa.service.Autocomplete.AutoCompleteResponse.Item>(results_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          me.world.usa.service.Autocomplete.AutoCompleteResponse.Item, me.world.usa.service.Autocomplete.AutoCompleteResponse.Item.Builder, me.world.usa.service.Autocomplete.AutoCompleteResponse.ItemOrBuilder> resultsBuilder_;

      /**
       * <code>repeated .me.world.usa.service.AutoCompleteResponse.Item results = 1;</code>
       */
      public java.util.List<me.world.usa.service.Autocomplete.AutoCompleteResponse.Item> getResultsList() {
        if (resultsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(results_);
        } else {
          return resultsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .me.world.usa.service.AutoCompleteResponse.Item results = 1;</code>
       */
      public int getResultsCount() {
        if (resultsBuilder_ == null) {
          return results_.size();
        } else {
          return resultsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .me.world.usa.service.AutoCompleteResponse.Item results = 1;</code>
       */
      public me.world.usa.service.Autocomplete.AutoCompleteResponse.Item getResults(int index) {
        if (resultsBuilder_ == null) {
          return results_.get(index);
        } else {
          return resultsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .me.world.usa.service.AutoCompleteResponse.Item results = 1;</code>
       */
      public Builder setResults(
          int index, me.world.usa.service.Autocomplete.AutoCompleteResponse.Item value) {
        if (resultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultsIsMutable();
          results_.set(index, value);
          onChanged();
        } else {
          resultsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .me.world.usa.service.AutoCompleteResponse.Item results = 1;</code>
       */
      public Builder setResults(
          int index, me.world.usa.service.Autocomplete.AutoCompleteResponse.Item.Builder builderForValue) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          results_.set(index, builderForValue.build());
          onChanged();
        } else {
          resultsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .me.world.usa.service.AutoCompleteResponse.Item results = 1;</code>
       */
      public Builder addResults(me.world.usa.service.Autocomplete.AutoCompleteResponse.Item value) {
        if (resultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultsIsMutable();
          results_.add(value);
          onChanged();
        } else {
          resultsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .me.world.usa.service.AutoCompleteResponse.Item results = 1;</code>
       */
      public Builder addResults(
          int index, me.world.usa.service.Autocomplete.AutoCompleteResponse.Item value) {
        if (resultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultsIsMutable();
          results_.add(index, value);
          onChanged();
        } else {
          resultsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .me.world.usa.service.AutoCompleteResponse.Item results = 1;</code>
       */
      public Builder addResults(
          me.world.usa.service.Autocomplete.AutoCompleteResponse.Item.Builder builderForValue) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          results_.add(builderForValue.build());
          onChanged();
        } else {
          resultsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .me.world.usa.service.AutoCompleteResponse.Item results = 1;</code>
       */
      public Builder addResults(
          int index, me.world.usa.service.Autocomplete.AutoCompleteResponse.Item.Builder builderForValue) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          results_.add(index, builderForValue.build());
          onChanged();
        } else {
          resultsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .me.world.usa.service.AutoCompleteResponse.Item results = 1;</code>
       */
      public Builder addAllResults(
          java.lang.Iterable<? extends me.world.usa.service.Autocomplete.AutoCompleteResponse.Item> values) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, results_);
          onChanged();
        } else {
          resultsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .me.world.usa.service.AutoCompleteResponse.Item results = 1;</code>
       */
      public Builder clearResults() {
        if (resultsBuilder_ == null) {
          results_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          resultsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .me.world.usa.service.AutoCompleteResponse.Item results = 1;</code>
       */
      public Builder removeResults(int index) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          results_.remove(index);
          onChanged();
        } else {
          resultsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .me.world.usa.service.AutoCompleteResponse.Item results = 1;</code>
       */
      public me.world.usa.service.Autocomplete.AutoCompleteResponse.Item.Builder getResultsBuilder(
          int index) {
        return getResultsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .me.world.usa.service.AutoCompleteResponse.Item results = 1;</code>
       */
      public me.world.usa.service.Autocomplete.AutoCompleteResponse.ItemOrBuilder getResultsOrBuilder(
          int index) {
        if (resultsBuilder_ == null) {
          return results_.get(index);  } else {
          return resultsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .me.world.usa.service.AutoCompleteResponse.Item results = 1;</code>
       */
      public java.util.List<? extends me.world.usa.service.Autocomplete.AutoCompleteResponse.ItemOrBuilder> 
           getResultsOrBuilderList() {
        if (resultsBuilder_ != null) {
          return resultsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(results_);
        }
      }
      /**
       * <code>repeated .me.world.usa.service.AutoCompleteResponse.Item results = 1;</code>
       */
      public me.world.usa.service.Autocomplete.AutoCompleteResponse.Item.Builder addResultsBuilder() {
        return getResultsFieldBuilder().addBuilder(
            me.world.usa.service.Autocomplete.AutoCompleteResponse.Item.getDefaultInstance());
      }
      /**
       * <code>repeated .me.world.usa.service.AutoCompleteResponse.Item results = 1;</code>
       */
      public me.world.usa.service.Autocomplete.AutoCompleteResponse.Item.Builder addResultsBuilder(
          int index) {
        return getResultsFieldBuilder().addBuilder(
            index, me.world.usa.service.Autocomplete.AutoCompleteResponse.Item.getDefaultInstance());
      }
      /**
       * <code>repeated .me.world.usa.service.AutoCompleteResponse.Item results = 1;</code>
       */
      public java.util.List<me.world.usa.service.Autocomplete.AutoCompleteResponse.Item.Builder> 
           getResultsBuilderList() {
        return getResultsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          me.world.usa.service.Autocomplete.AutoCompleteResponse.Item, me.world.usa.service.Autocomplete.AutoCompleteResponse.Item.Builder, me.world.usa.service.Autocomplete.AutoCompleteResponse.ItemOrBuilder> 
          getResultsFieldBuilder() {
        if (resultsBuilder_ == null) {
          resultsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              me.world.usa.service.Autocomplete.AutoCompleteResponse.Item, me.world.usa.service.Autocomplete.AutoCompleteResponse.Item.Builder, me.world.usa.service.Autocomplete.AutoCompleteResponse.ItemOrBuilder>(
                  results_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          results_ = null;
        }
        return resultsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:me.world.usa.service.AutoCompleteResponse)
    }

    // @@protoc_insertion_point(class_scope:me.world.usa.service.AutoCompleteResponse)
    private static final me.world.usa.service.Autocomplete.AutoCompleteResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new me.world.usa.service.Autocomplete.AutoCompleteResponse();
    }

    public static me.world.usa.service.Autocomplete.AutoCompleteResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AutoCompleteResponse>
        PARSER = new com.google.protobuf.AbstractParser<AutoCompleteResponse>() {
      @java.lang.Override
      public AutoCompleteResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AutoCompleteResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AutoCompleteResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AutoCompleteResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public me.world.usa.service.Autocomplete.AutoCompleteResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_world_usa_service_AutoCompleteResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_world_usa_service_AutoCompleteResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_world_usa_service_AutoCompleteResponse_Item_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_world_usa_service_AutoCompleteResponse_Item_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022autocomplete.proto\022\024me.world.usa.servi" +
      "ce\"\216\001\n\024AutoCompleteResponse\022@\n\007results\030\001" +
      " \003(\0132/.me.world.usa.service.AutoComplete" +
      "Response.Item\0324\n\004Item\022\013\n\003url\030\001 \001(\t\022\r\n\005ti" +
      "tle\030\002 \001(\t\022\020\n\010snippets\030\003 \003(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_me_world_usa_service_AutoCompleteResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_me_world_usa_service_AutoCompleteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_world_usa_service_AutoCompleteResponse_descriptor,
        new java.lang.String[] { "Results", });
    internal_static_me_world_usa_service_AutoCompleteResponse_Item_descriptor =
      internal_static_me_world_usa_service_AutoCompleteResponse_descriptor.getNestedTypes().get(0);
    internal_static_me_world_usa_service_AutoCompleteResponse_Item_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_world_usa_service_AutoCompleteResponse_Item_descriptor,
        new java.lang.String[] { "Url", "Title", "Snippets", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
